### ISSUE TITLE
Image size problem

### ISSUE THREAD

**Issue by jieeeeeeeeeee** [xy-guo/GwcNet#10]
I am trying to use gwcNet to test other datasets in kiiti. But the size of image  is 1392＊512．
When i run the program, i got error message: assert top_pad > 0 and right_pad > 0.
I find that:
```python
top_pad = 384 - h
right_pad = 1248 - w
assert top_pad > 0 and right_pad > 0
```
Is the image size must be lower than 1248*384 ?
What will happen, if i comment the 'assert top_pad > 0 and right_pad > 0' like:

```python
＃assert top_pad > 0 and right_pad > 0
```

Thank you very much.

**Comment by xy-guo** [comment]
You can update the code to 
```
top_pad = int(ceil(h / 32.) * 32) - h   # from math import ceil
right_pad = int(ceil(w / 32.) * 32) - w
```

The padding is to pad the input to an integer multiple of h and w

**Comment by jieeeeeeeeeee** [comment]
I try your code, it runs good :). 
```python

# pad to size 1248x384
#top_pad = 384 - h
#right_pad = 1248 - w
#assert top_pad > 0 and right_pad > 0   

top_pad = int(np.ceil(h / 32.) * 32) - h   # from math import ceil
right_pad = int(np.ceil(w / 32.) * 32) - w

assert top_pad >= 0 and right_pad >= 0
```

But when i run an image which size is 1280*720. I catch an error:

> saving to predictions/0000000000.png (720, 0)

So i modify the code:
```python
#disp_est = np.array(disp_est[top_pad:, :-right_pad], dtype=np.float32)  

if right_pad == 0:
    disp_est = np.array(disp_est[top_pad:, :], dtype=np.float32)
else:
    disp_est = np.array(disp_est[top_pad:, :-right_pad], dtype=np.float32)
```
It runs good finally!

Thank you !
