### ISSUE TITLE
您好，有几个问题想向您请教。

### ISSUE THREAD

**Issue by fighterzzzh** [xy-guo/GwcNet#11]
我刚跑完了自己修改过的psmn的代码，但显卡受限，batchsize=1，结果不是很好。
请问您如果使用batchsize=1是不是效果会不理想？
另外如果batchsize=1，BatchNormalization是否会有作用？
还有一个问题，为什么不把kitti2012也作为预训练，然后去训练kitti2015呢。我打算去做这件事。
问题有点多哈，如您能万分忙碌之中抽空回答，万分感谢。

**Comment by xy-guo** [comment]
1的话应该会差很多，因为训练时的前传计算到均值回不太准确

**Comment by xy-guo** [comment]
如果纯粹为了刷性能的话，用kitti12/15都训练下没啥问题，但是为了和之前算法公平对比的话，还是不要这么做。

**Comment by fighterzzzh** [comment]
好的，谢谢
