### ISSUE TITLE
前辈您好，想请教您关于KITTI数据集评价标准的一些问题~

### ISSUE THREAD

**Issue by tjutzdd** [xy-guo/GwcNet#13]
请问，KITTI15的评价标准里面的 All(%)是否对应于用到的ground truth(disp_occ_0和disp_occ_1)，以及Noc(%)对应于用到的ground truth(disp_noc_0和disp_noc_1)呢？

D1评价标准的函数您代码里已经给出来了，但是D1-bg  D1-fg  D1-all 这些是怎么计算的，有没有相应的计算方法呢？很是不明白，请前辈多多指教！~~~

蟹蟹~~~

**Comment by xy-guo** [comment]
是的，可以提交结果到kitti网站，然后可以查看你的模型性能

**Comment by tjutzdd** [comment]
好的！多谢前辈帮助~~~
