### ISSUE TITLE
the problem about submit result on "KITTI Evaluation Benchmark "

### ISSUE THREAD

**Issue by wenyang1112** [xy-guo/GwcNet#17]
I submit my result on stereo 2015, then I receive a letter from "KITTI Evaluation Benchmark ", it give me a link to check the result. But when I click the link, it show me the error: ERROR: Result key 3708644dc4ab21dc7e6405e2d0c2d31f835 not registered with user fe4d4b5364cb33b1b410d3d27e2aae1. I don't know how to solve it. Could you give me some advice? Thank you!
ps: my zip only include disp_0 floder, because I just want to submit the stereo 2015 test set result

**Comment by xy-guo** [comment]
Sorry, I'm not familiar with this error.

**Comment by wenyang1112** [comment]
感谢您的回复，我想再问一下，在kitti上提交结果需要翻墙吗？能够收到结果邮件（虽然打开连接出现了错误）是不是就意味着不需要翻墙呢？
 &nbsp;
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Xiaoyang Guo"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年12月16日(星期一) 中午11:01
 收件人:&nbsp;"xy-guo/GwcNet"<GwcNet@noreply.github.com&gt;;
 抄送:&nbsp;"wy"<2453079161@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [xy-guo/GwcNet] the problem about submit result on "KITTI Evaluation Benchmark " (#17)

 

 
Sorry, I'm not familiar with this error.
