### ISSUE TITLE
作者@xy-guo您好！对于SceneFlow数据集的目录结果的设置想向您求教一下。

### ISSUE THREAD

**Issue by tjutzdd** [xy-guo/GwcNet#2]
作者您好，非常感谢您贡献过的代码！很激动！
对于SceneFlow数据集，您用的是Finalpass，我这里想用Cleanpass但是不知道目录结构怎么设置，运行脚本文件总是提示找不到目录。
希望能够得到您的解答，谢谢！！！

**Comment by xy-guo** [comment]
你可以尝试生成自己的列表。
我的数据是把monkaa和drivings的数据都移动到了TRAIN里

**Comment by tjutzdd** [comment]
非常感谢@xy-guo您的解答！~~
看了您代码里的数据集.txt文档我就明白了，换数据集的话只需要生成自己的数据地址列表到txt文档中，然后注意加载的路径以及文档的名字。具体的sceneflow_dataset.py代码好像不用更改吧。
上述就是我的理解，谢谢作者您能够抽出您宝贵的时间为我解答！
万分感谢！！！
