### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for DataParallel:

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [xy-guo/GwcNet#22]
Hi,

I am getting the following error on using the Kitti 2015 checkpoint:

RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.feature_extraction.lastconv.0.0.weight", "module.feature_extraction.lastconv.0.1.weight", "module.feature_extraction.lastconv.0.1.bias", "module.feature_extraction.lastconv.0.1.running_mean", "module.feature_extraction.lastconv.0.1.running_var", "module.feature_extraction.lastconv.2.weight". 
	size mismatch for module.dres0.0.0.weight: copying a param with shape torch.Size([32, 40, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 64, 3, 3, 3]).

**Comment by xy-guo** [comment]
Please set correct model type (gwcnet-gc or gwcnet-g)
