### ISSUE TITLE
用自己的图片测试时，维度不匹配问题。

### ISSUE THREAD

**Issue by liuwenbo4795** [xy-guo/GwcNet#23]
你好，我加载了自己的一张图片，运行时，在gwcnet.py文件中的hourglass类里面的forward函数里，出现数据维度不匹配问题。
“RuntimeError: The size of tensor a (82) must match the size of tensor b (81) at non-singleton dimension 4”
我把forward函数里所有数据的尺寸都打印了一下，发现了问题：
def forward(self, x):
        conv1 = self.conv1(x)      #torch.Size([1, 64, 24, 70, 81])
        conv2 = self.conv2(conv1)  #torch.Size([1, 64, 24, 70, 81])
        conv3 = self.conv3(conv2)  #torch.Size([1, 128, 12, 35, 41])
        conv4 = self.conv4(conv3)  #torch.Size([1, 128, 12, 35, 41])
        # print(self.conv5(conv4).size())  # torch.Size([1, 64, 24, 70, 82])<-------([1, 128, 12, 35, 41])
        # print(self.redir2(conv2).size()) # torch.Size([1, 64, 24, 70, 81])
        conv5 = F.relu(self.conv5(conv4) + self.redir2(conv2), inplace=True)
        conv6 = F.relu(self.conv6(conv5) + self.redir1(x), inplace=True)
        return conv6
是self.conv5(conv4)和self.redir2(conv2)最后一维尺寸不一样，请问这个问题应该怎么解决呢？

**Comment by xy-guo** [comment]
You can pad your image to be divisible by 64 (or 32). (Sry I didn't install input methods.)
