### ISSUE TITLE
huge gpu memory consume

### ISSUE THREAD

**Issue by forvd** [xy-guo/GwcNet#4]
I tried to train on TITAN(12GB Total), but it always went out of memory. Not even batch_size = 1.Is that normal?

**Comment by xy-guo** [comment]
For each image, it consumes around 4.2GB memory on average. You may need to set both `batch_size` and `test_batch_size` to 1.

**Comment by forvd** [comment]
sry, i modified some of the code and forget about it, that cause the problem. 
But I also want to know about memory consumption in inference.

**Comment by xy-guo** [comment]
The inference memory depends on the input size and the code. I forgot the
accurate memory consumption in the inference mode
