### ISSUE TITLE
About the pretrained model on sceneflow dataset

### ISSUE THREAD

**Issue by XGBoost** [xy-guo/GwcNet#5]
Thank for your codes!
In your paper, you have mentioned that experiments on kitt12 and kitt15 are finetuned using the pre-trained model on scene flow. HIt is very slow when I download the scene flow dataset. So I want to train the network on kitti12 directly.
However I didn't find the pre-trained model on scene flow, could you please provide that pre-trained model, thank you very much!

**Comment by xy-guo** [comment]
Updated.
