### ISSUE TITLE
How to get .\checkpoints\kitti12\gwcnet-gc\best.ckpt.

### ISSUE THREAD

**Issue by jieeeeeeeeeee** [xy-guo/GwcNet#8]
Dear guo
Is there a pretrained model provided ?
Could you please provid a pre-trained model?
Thanks

**Comment by xy-guo** [comment]
Please find the download link in README

**Comment by jieeeeeeeeeee** [comment]
Oh, i found it. It is at [KITTI 2012/2015](https://drive.google.com/file/d/1fOw2W7CSEzvSKzBAEIIeftxw6CuvH9Hl/view). Thank you very much.
